services:
  coins-kids-shop:
    build: .
    container_name: coins-kids-shop
    environment:
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
