CREATE TABLE application_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    family_id INTEGER NOT NULL,
    child_id INTEGER NOT NULL,
    request_id BIGINT,
    coin_delta INTEGER NOT NULL DEFAULT 0,
    resulting_balance INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    planning_claimed_at TIMESTAMP WITH TIME ZONE,
    planning_completed_at TIMESTAMP WITH TIME ZONE,
    planning_status VARCHAR(32) NOT NULL DEFAULT 'UNPLANNED'
);
CREATE TABLE telegram_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    recipient_identity_id INTEGER NOT NULL,
    chat_id BIGINT NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_at TIMESTAMP WITH TIME ZONE,
    sent_at TIMESTAMP WITH TIME ZONE,
    terminal_at TIMESTAMP WITH TIME ZONE,
    message_id BIGINT,
    last_error VARCHAR(500),
    CONSTRAINT uq_telegram_delivery_event_recipient UNIQUE (event_id, recipient_identity_id)
);
