import {
    Activity,
    Archive,
    ArrowLeft,
    ArrowRight,
    BookOpen,
    Bell,
    Castle,
    Check,
    ChevronDown,
    CircleCheck,
    CircleDollarSign,
    ClipboardList,
    Coins,
    Dice5,
    FlaskConical,
    Gift,
    Heart,
    History,
    House,
    Link,
    Minus,
    MoreHorizontal,
    Package,
    Pencil,
    Plus,
    RefreshCw,
    SlidersHorizontal,
    Smartphone,
    Sparkles,
    Shield,
    Sun,
    Table,
    Tag,
    Trash2,
    TriangleAlert,
    UserRound,
    UserRoundPlus,
    Users,
    UsersRound,
    X
} from '@lucide/svelte';

export const telegramIconMap = {
    approve: Check,
    reject: X,
    done: Check,
    requestReward: Gift,
    coinAdjustment: CircleDollarSign,
    childSwitch: RefreshCw,
    refresh: RefreshCw,
    openApp: Smartphone,
    back: ArrowLeft,
    filter: SlidersHorizontal,
    add: Plus,
    edit: Pencil,
    archive: Archive,
    delete: Trash2,
    task: ClipboardList,
    reward: Gift,
    request: Tag,
    gift: Gift,
    tag: Tag,
    activity: Activity,
    family: UsersRound,
    balance: CircleDollarSign,
    history: History,
    child: UserRound,
    remove: Minus,
    home: House,
    arrowRight: ArrowRight,
    // ── semantic entity graphics ──────────────────────────────────────────
    sun: Sun,
    book: BookOpen,
    pencil: Pencil,
    sparkles: Sparkles,
    dice: Dice5,
    flask: FlaskConical,
    castle: Castle,
    heart: Heart,
    users: Users,
    coin: Coins,
    checkCircle: CircleCheck,
    alert: TriangleAlert,
    box: Package,
    desk: Table,
    addChild: UserRoundPlus,
    chevronDown: ChevronDown,
    more: MoreHorizontal,
    shield: Shield,
    link: Link,
    bell: Bell
} as const;

export type TelegramIconName = keyof typeof telegramIconMap;
