import {
    Activity,
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Award,
    Bath,
    BedSingle,
    Bell,
    Bike,
    Blocks,
    BookOpen,
    Brush,
    Cake,
    Calculator,
    Calendar,
    Car,
    Castle,
    Check,
    ChevronDown,
    CircleCheck,
    CircleDollarSign,
    CircleDot,
    CirclePause,
    CirclePlay,
    CircleQuestionMark,
    ClipboardList,
    Clock,
    Coins,
    CookingPot,
    Copy,
    Dice5,
    Droplet,
    Dumbbell,
    Eye,
    FileText,
    Film,
    FlaskConical,
    Footprints,
    Gamepad2,
    Gauge,
    Gift,
    Heart,
    History,
    House,
    IceCreamCone,
    Infinity as InfinityIcon,
    Key,
    Languages,
    Link,
    ListChecks,
    ListOrdered,
    Mail,
    Medal,
    Minus,
    Moon,
    MoreHorizontal,
    Music,
    Package,
    Palette,
    PawPrint,
    Pencil,
    PencilLine,
    PenTool,
    PiggyBank,
    Plus,
    RefreshCw,
    School,
    Search,
    Send,
    Shield,
    Shirt,
    ShowerHead,
    SlidersHorizontal,
    Smartphone,
    Sparkles,
    Sprout,
    Star,
    Sun,
    Sunrise,
    Table,
    Tag,
    Target,
    Trash2,
    TreePine,
    Trees,
    TriangleAlert,
    Trophy,
    Unlink,
    Upload,
    UserRound,
    UserRoundPlus,
    Users,
    UsersRound,
    Utensils,
    UtensilsCrossed,
    Volleyball,
    X
} from '@lucide/svelte';

export const telegramIconMap = {
    approve: Check,
    reject: X,
    done: Check,
    check: Check,
    requestReward: Gift,
    coinAdjustment: CircleDollarSign,
    childSwitch: RefreshCw,
    refresh: RefreshCw,
    search: Search,
    openApp: Smartphone,
    back: ArrowLeft,
    filter: SlidersHorizontal,
    add: Plus,
    edit: Pencil,
    archive: Archive,
    delete: Trash2,
    task: ClipboardList,
    reward: Gift,
    request: Tag,
    gift: Gift,
    tag: Tag,
    activity: Activity,
    family: UsersRound,
    balance: CircleDollarSign,
    history: History,
    child: UserRound,
    remove: Minus,
    home: House,
    arrowRight: ArrowRight,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    reorder: ListOrdered,
    selectSeveral: ListChecks,
    sun: Sun,
    book: BookOpen,
    pencil: Pencil,
    sparkles: Sparkles,
    dice: Dice5,
    flask: FlaskConical,
    castle: Castle,
    heart: Heart,
    users: Users,
    coin: Coins,
    checkCircle: CircleCheck,
    alert: TriangleAlert,
    box: Package,
    desk: Table,
    addChild: UserRoundPlus,
    chevronDown: ChevronDown,
    more: MoreHorizontal,
    shield: Shield,
    link: Link,
    bell: Bell,
    upload: Upload,
    mail: Mail,
    gauge: Gauge,
    pause: CirclePause,
    play: CirclePlay,
    send: Send,
    key: Key,
    eye: Eye,
    copy: Copy,
    file: FileText,
    unlink: Unlink,
    sunrise: Sunrise,
    moon: Moon,
    bed: BedSingle,
    shower: ShowerHead,
    shirt: Shirt,
    utensils: Utensils,
    utensilsCrossed: UtensilsCrossed,
    droplet: Droplet,
    pencilLine: PencilLine,
    calculator: Calculator,
    school: School,
    languages: Languages,
    music: Music,
    table: Table,
    sprout: Sprout,
    paw: PawPrint,
    dumbbell: Dumbbell,
    bike: Bike,
    footprints: Footprints,
    film: Film,
    gamepad: Gamepad2,
    palette: Palette,
    penTool: PenTool,
    blocks: Blocks,
    treePine: TreePine,
    trees: Trees,
    iceCream: IceCreamCone,
    cake: Cake,
    car: Car,
    infinity: InfinityIcon,
    piggy: PiggyBank,
    medal: Medal,
    award: Award,
    trophy: Trophy,
    star: Star,
    target: Target,
    calendar: Calendar,
    clock: Clock,
    volleyball: Volleyball,
    brush: Brush,
    cookingPot: CookingPot,
    bath: Bath,
    circleDot: CircleDot,
    questionMark: CircleQuestionMark
} as const;

export type TelegramIconName = keyof typeof telegramIconMap;
