package com.sashplatonov.earnit.kids.platform.infrastructure.persistence;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Instant;
import java.util.Arrays;
import java.util.Objects;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;

class TimestampRepairMigrationTest {

    @Test
    void migrationRepairsMillisecondAndSecondIdsWithoutTouchingOtherRows() throws Exception {
        String jdbcUrl = "jdbc:h2:mem:timestamp-repair-" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "")) {
            createTables(connection);

            Instant millisecondInstant = Instant.parse("2024-04-17T09:30:15Z");
            Instant secondInstant = Instant.parse("2024-04-16T07:45:00Z");
            Instant untouchedInstant = Instant.parse("2026-04-17T12:00:00Z");
            Instant wrongInstant = Instant.parse("2026-04-17T20:00:00Z");

            insertRow(connection, "history", millisecondInstant.toEpochMilli(), wrongInstant);
            insertRow(connection, "history", secondInstant.getEpochSecond(), wrongInstant);
            insertRow(connection, "history", 12345L, untouchedInstant);

            insertRow(connection, "requests", millisecondInstant.toEpochMilli(), wrongInstant);
            insertRow(connection, "requests", secondInstant.getEpochSecond(), null);
            insertRow(connection, "requests", 67890L, untouchedInstant);

            executeMigration(connection, "db/migration/V6__expand_timestamp_repair_coverage.sql");

            assertThat(readCreatedAt(connection, "history", millisecondInstant.toEpochMilli())).isEqualTo(millisecondInstant);
            assertThat(readCreatedAt(connection, "history", secondInstant.getEpochSecond())).isEqualTo(secondInstant);
            assertThat(readCreatedAt(connection, "history", 12345L)).isEqualTo(untouchedInstant);

            assertThat(readCreatedAt(connection, "requests", millisecondInstant.toEpochMilli())).isEqualTo(millisecondInstant);
            assertThat(readCreatedAt(connection, "requests", secondInstant.getEpochSecond())).isEqualTo(secondInstant);
            assertThat(readCreatedAt(connection, "requests", 67890L)).isEqualTo(untouchedInstant);
        }
    }

    private void createTables(Connection connection) throws Exception {
        executeStatement(connection,
            "CREATE TABLE history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id BIGINT, created_at TIMESTAMP WITH TIME ZONE)");
        executeStatement(connection,
            "CREATE TABLE requests (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id BIGINT, created_at TIMESTAMP WITH TIME ZONE)");
    }

    private void insertRow(Connection connection, String tableName, long externalId, Instant createdAt) throws Exception {
        try (PreparedStatement statement = connection.prepareStatement(
            "INSERT INTO " + tableName + " (external_id, created_at) VALUES (?, ?)")) {
            statement.setLong(1, externalId);
            statement.setObject(2, createdAt);
            statement.executeUpdate();
        }
    }

    private Instant readCreatedAt(Connection connection, String tableName, long externalId) throws Exception {
        try (PreparedStatement statement = connection.prepareStatement(
            "SELECT created_at FROM " + tableName + " WHERE external_id = ?")) {
            statement.setLong(1, externalId);
            try (ResultSet resultSet = statement.executeQuery()) {
                assertThat(resultSet.next()).isTrue();
                return resultSet.getObject(1, java.time.OffsetDateTime.class).toInstant();
            }
        }
    }

    private void executeMigration(Connection connection, String resourceName) throws Exception {
        String sql = readSqlResource(resourceName);
        for (String statement : sql.split(";")) {
            String trimmed = statement.trim();
            if (!trimmed.isEmpty()) {
                executeStatement(connection, trimmed);
            }
        }
    }

    private String readSqlResource(String resourceName) throws IOException {
        try (InputStream inputStream = getClass().getClassLoader().getResourceAsStream(resourceName)) {
            Objects.requireNonNull(inputStream, resourceName);
            String content = new String(inputStream.readAllBytes(), StandardCharsets.UTF_8);
            return Arrays.stream(content.split("\\R"))
                .filter(line -> !line.stripLeading().startsWith("--"))
                .collect(Collectors.joining("\n"));
        }
    }

    private void executeStatement(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
